server:
  port: 8085

spring:
  application:
    name: membership
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cheersai}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:021003st}
  flyway:
    enabled: false

mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
