server:
  port: 8080

spring:
  application:
    name: membership
  
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false

mybatis-flex:
  db-type: postgresql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
